name: digital_pamphlet
description: A new Flutter project.
publish_to: 'none'
version: 0.1.7+8

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  get_it: ^7.3.0
  go_router: ^6.5.8
  injectable: ^2.1.1
  intl: ^0.18.1
  json_annotation: ^4.8.0
  logger: ^1.3.0
  retrofit: ^4.0.1
  stream_transform: ^2.1.0
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  retrofit_generator: ^6.0.0+3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100

flutter_launcher_icons:
  image_path: 'assets/icon/icon.png'
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  background_image: assets/icon/splash.png
